import type { Metadata } from "next";
import { Nunito, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";

import { TemplateProvider } from "@/lib/template-context";

import "./globals.css";

const nunito = Nunito({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diyo AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang='en'
      className={`${nunito.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <TemplateProvider>{children}</TemplateProvider>
      </body>
    </html>
  );
}
